### ISSUE TITLE
preshed.maps wheel

### ISSUE THREAD

**Issue by jimanvlad** [explosion/preshed#13]
Hi,

I am trying to install spacy from a .whl, and one of the requirements (preshed) is causing a whole lot of trouble.

I downloaded the preshed wheel from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/) but unfortunately when installing it, it says that building "preshed.maps" failed given that I have no C++ compiler installed.

Are you able to provide a .whl for preshed.maps?

Vlad

**Comment by rolando** [comment]
FYI, preshed (as well as spacy) are available via [conda](https://conda.io/docs/). See
* https://github.com/conda-forge/preshed-feedstock#current-build-status 
* https://github.com/conda-forge/spacy-feedstock#current-build-status

**Comment by AugustT** [comment]
I'm also having issues with this, conda install does not help as I still get 

```
ImportError: Building module preshed.maps failed: ['DistutilsPlatformError: Unable to find vcvarsall.bat\n']
```

**Comment by adrianeboyd** [comment]
Just cleaning up old issues: binary packages are available for most platforms on pypi and conda-forge and the most recent releases hopefully make source installs easier, although you would still need a compiler for the source install.
