### ISSUE TITLE
pip install preshed fails for official python:3.7 docker container

### ISSUE THREAD

**Issue by jtmoulia** [explosion/preshed#15]
Hi, I'm trying to install spacy in the official [python:3.7](https://store.docker.com/images/python) docker container but I'm getting an error: `Failed building wheel for cymem`.

Here's the command and the [full log](https://pastebin.com/D8xk6y5y):

```
docker run -it --rm python:3.7 bash -c 'pip install preshed'
```

Note that running this command using the `python:3.6` container works fine.

Let me know if any additional information would be useful!

**Comment by Russell-Jones-OxPhys** [comment]
preshed fails at
```
    preshed/maps.cpp:6647:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tstate->exc_traceback = *tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
which (googleficially) looks like https://github.com/pandas-dev/pandas/issues/21785

**Comment by jtmoulia** [comment]
Thanks for the tip @Russell-Jones-OxPhys -- I think the issue underlying both is the old version of Cython.

**Comment by honnibal** [comment]
Thanks @jtmoulia , seems to be the case
